spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root


sym:
  security:
    code:
      imageHeight: 22

server:
  session:
    timeout: 60 #springBoot的默认session会话过期最小1分钟，我们在这里可以配置大于1分钟的过期时间，单位为s
